import type {
  Profile,
  UserSession,
  PasswordHistory,
  AuthAuditLog,
  Subject,
  Chapter,
  Topic,
  SourceDocument,
  SourcePage,
  ExamBlueprint,
  Question,
  QuestionChoice,
  QuestionAnswerKey,
  QuestionSource,
  QuestionQualityFlag,
  ExamAttempt,
  AttemptQuestion,
  AttemptAnswer,
  Bookmark,
  AdminAuditLog,
  GenerationRun,
} from '../types/database';
import internetworkingData from './internetworking-data.json';

export interface DataStore {
  profiles: Profile[];
  user_sessions: UserSession[];
  password_history: PasswordHistory[];
  auth_audit_logs: AuthAuditLog[];
  subjects: Subject[];
  chapters: Chapter[];
  topics: Topic[];
  source_documents: SourceDocument[];
  source_pages: SourcePage[];
  exam_blueprints: ExamBlueprint[];
  questions: Question[];
  question_choices: QuestionChoice[];
  question_answer_keys: QuestionAnswerKey[];
  question_sources: QuestionSource[];
  question_quality_flags: QuestionQualityFlag[];
  exam_attempts: ExamAttempt[];
  attempt_questions: AttemptQuestion[];
  attempt_answers: AttemptAnswer[];
  bookmarks: Bookmark[];
  admin_audit_logs: AdminAuditLog[];
  generation_runs: GenerationRun[];
}

export function createInitialSeedData(): DataStore {
  // Base Production Accounts
  const studentUser: Profile = {
    id: 'u-student-001',
    email: 'student@example.com',
    full_name: 'สมชาย รักเรียน',
    role: 'student',
    is_email_verified: true,
    password_hash: 'Password123!',
    failed_login_attempts: 0,
    locked_until: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const adminUser: Profile = {
    id: 'u-admin-001',
    email: 'admin@example.com',
    full_name: 'ดร. วิชาญ ผู้ดูแลระบบ',
    role: 'admin',
    is_email_verified: true,
    password_hash: 'Admin123!',
    failed_login_attempts: 0,
    locked_until: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const inet = internetworkingData as any;

  const extraQuestions: Question[] = [
    {
      id: 'q-fib-001',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-01',
      topic_id: 'top-inet-01-1',
      chapter_title: 'Packet Forwarding',
      topic_title: 'Network Device Communication & OSI',
      question_text: 'ในสถาปัตยกรรม TCP/IP โมเดล ชั้น [blank_1] รับผิดชอบการส่งข้อมูลแบบ End-to-End โดยมีโปรโตคอลแบบเน้นความน่าเชื่อถือคือ [blank_2] และโปรโตคอลที่เน้นความรวดเร็วคือ [blank_3] ส่วนชั้น [blank_4] รับผิดชอบการค้นหาเส้นทาง (Routing) ข้ามเครือข่าย',
      question_type: 'fill_in_the_blank',
      difficulty: 'medium',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'Transport Layer',
        'TCP',
        'UDP',
        'Network Layer',
        'Data Link Layer',
        'IP',
        'HTTP',
        'Physical Layer',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'ชั้นการทำงานหลัก', correct_word: 'Transport Layer' },
        { id: 'blank_2', position: 2, placeholder: 'โปรโตคอลเน้นความถูกต้อง', correct_word: 'TCP' },
        { id: 'blank_3', position: 3, placeholder: 'โปรโตคอลเน้นความเร็ว', correct_word: 'UDP' },
        { id: 'blank_4', position: 4, placeholder: 'ชั้นค้นหาเส้นทาง', correct_word: 'Network Layer' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-fib-002',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-01',
      topic_id: 'top-inet-01-4',
      chapter_title: 'Packet Forwarding',
      topic_title: 'Forwarding Architectures (CEF, TCAM, SDM)',
      question_text: 'ในกลไกการส่งต่อแพ็กเก็ตแบบ Cisco Express Forwarding (CEF) ตาราง [blank_1] ถูกสร้างขึ้นมาจาก Routing Table เพื่อใช้ค้นหา Prefix ปลายทางที่ความเร็วระดับฮาร์ดแวร์ และตาราง [blank_2] เก็บข้อมูล Layer 2 Rewrite Header สำหรับ Next-Hop โดยข้อมูลทั้งหมดถูกโหลดเข้าหน่วยความจำพิเศษแบบ [blank_3]',
      question_type: 'fill_in_the_blank',
      difficulty: 'hard',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'FIB (Forwarding Information Base)',
        'Adjacency Table',
        'TCAM',
        'RIB (Routing Information Base)',
        'CAM Table',
        'ARP Table',
        'Process Switching',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'ตารางค้นหา L3 Prefix', correct_word: 'FIB (Forwarding Information Base)' },
        { id: 'blank_2', position: 2, placeholder: 'ตาราง L2 Next-Hop Header', correct_word: 'Adjacency Table' },
        { id: 'blank_3', position: 3, placeholder: 'หน่วยความจำค้นหาความเร็วสูง', correct_word: 'TCAM' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-fib-003',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-02',
      topic_id: 'top-inet-02-1',
      chapter_title: 'Spanning Tree Protocol',
      topic_title: 'STP Fundamentals & Port States',
      question_text: 'ใน Spanning Tree Protocol มาตรฐานดั้งเดิม (802.1D) เมื่อพอร์ตเปลี่ยนจากสถานะ Blocking จะเข้าสู่สถานะ [blank_1] เพื่อรับฟัง BPDU และสร้าง Topology เป็นเวลา 15 วินาที จากนั้นเปลี่ยนเป็นสถานะ [blank_2] เพื่อเริ่มเรียนรู้ MAC Address อีก 15 วินาที ก่อนจะเข้าสู่สถานะ [blank_3] ที่สามารถส่งผ่าน Frame ข้อมูลได้ตามปกติ',
      question_type: 'fill_in_the_blank',
      difficulty: 'medium',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'Listening',
        'Learning',
        'Forwarding',
        'Blocking',
        'Disabled',
        'Discarding',
        'Filtering',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'สถานะรับฟัง BPDU', correct_word: 'Listening' },
        { id: 'blank_2', position: 2, placeholder: 'สถานะเรียนรู้ MAC Address', correct_word: 'Learning' },
        { id: 'blank_3', position: 3, placeholder: 'สถานะส่งต่อข้อมูล', correct_word: 'Forwarding' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-fib-004',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-05',
      topic_id: 'top-inet-05-3',
      chapter_title: 'VLAN Trunks and EtherChannel Bundles',
      topic_title: 'EtherChannel with PAgP & LACP',
      question_text: 'การรวมพอร์ต EtherChannel ตามมาตรฐานสากล IEEE 802.3ad ใช้โปรโตคอล [blank_1] โดยมีโหมด [blank_2] เป็นฝ่ายเริ่มต้นส่งแพ็กเก็ตเจรจา และโหมด [blank_3] เป็นฝ่ายรอรับการเจรจา ส่วนโปรโตคอลที่เป็นกรรมสิทธิ์ของ Cisco คือ [blank_4]',
      question_type: 'fill_in_the_blank',
      difficulty: 'medium',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'LACP',
        'Active',
        'Passive',
        'PAgP',
        'Desirable',
        'Auto',
        'On',
        'DTP',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'โปรโตคอลมาตรฐาน IEEE', correct_word: 'LACP' },
        { id: 'blank_2', position: 2, placeholder: 'โหมดเริ่มเจรจา (LACP)', correct_word: 'Active' },
        { id: 'blank_3', position: 3, placeholder: 'โหมดรอรับเจรจา (LACP)', correct_word: 'Passive' },
        { id: 'blank_4', position: 4, placeholder: 'โปรโตคอลของ Cisco', correct_word: 'PAgP' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-fib-005',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-06',
      topic_id: 'top-inet-06-1',
      chapter_title: 'IP Routing Essentials',
      topic_title: 'Routing Fundamentals & Path Selection',
      question_text: 'ในตาราง Routing Table ของ Cisco ค่า [blank_1] ใช้จัดลำดับความน่าเชื่อถือของแหล่งที่มาของเส้นทาง โดยเส้นทางแบบ Static Route มีค่าเป็น [blank_2] ส่วนโปรโตคอล Internal EIGRP มีค่าเป็น [blank_3] และ OSPF มีค่าเป็น [blank_4]',
      question_type: 'fill_in_the_blank',
      difficulty: 'easy',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'Administrative Distance',
        '1',
        '90',
        '110',
        'Metric',
        '0',
        '120',
        '20',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'ค่าลำดับความน่าเชื่อถือ', correct_word: 'Administrative Distance' },
        { id: 'blank_2', position: 2, placeholder: 'AD ของ Static Route', correct_word: '1' },
        { id: 'blank_3', position: 3, placeholder: 'AD ของ EIGRP Internal', correct_word: '90' },
        { id: 'blank_4', position: 4, placeholder: 'AD ของ OSPF', correct_word: '110' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-fib-006',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-07',
      topic_id: 'top-inet-07-2',
      chapter_title: 'EIGRP',
      topic_title: 'EIGRP Metrics & Feasibility Condition',
      question_text: 'ในโปรโตคอล EIGRP เงื่อนไข Feasibility Condition กำหนดว่าเส้นทางสำรองจะเป็น Feasible Successor ได้ก็ต่อเมื่อค่า [blank_1] ของ Neighbor ต้องมีค่าน้อยกว่าค่า [blank_2] ของ Successor ปัจจุบัน เพื่อป้องกันไม่ให้เกิดปัญหา [blank_3]',
      question_type: 'fill_in_the_blank',
      difficulty: 'hard',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'Reported Distance (RD)',
        'Feasible Distance (FD)',
        'Routing Loop',
        'Administrative Distance',
        'Hop Count',
        'Bandwidth Metric',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'ค่าระยะที่ Neighbor รายงาน', correct_word: 'Reported Distance (RD)' },
        { id: 'blank_2', position: 2, placeholder: 'ค่าระยะที่ดีที่สุดปัจจุบัน', correct_word: 'Feasible Distance (FD)' },
        { id: 'blank_3', position: 3, placeholder: 'ปัญหาที่ป้องกัน', correct_word: 'Routing Loop' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-fib-007',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-11',
      topic_id: 'top-inet-11-2',
      chapter_title: 'BGP',
      topic_title: 'BGP Path Attributes & Best-Path Selection',
      question_text: 'ในการเลือกเส้นทาง Best Path ของ Cisco BGP พารามิเตอร์แรกที่ตรวจสอบคือ [blank_1] (Cisco proprietary, ยิ่งมากยิ่งดี) ตามด้วยค่า [blank_2] ซึ่งส่งต่อภายใน AS เดียวกัน (ค่าดีฟอลต์ 100) และหากยังเท่ากันจะพิจารณาเส้นทางที่สร้างขึ้นเอง (Locally Originated) ก่อนตรวจสอบความยาวของ [blank_3] ที่สั้นที่สุด',
      question_type: 'fill_in_the_blank',
      difficulty: 'hard',
      status: 'published',
      is_ai_generated: false,
      word_bank: [
        'Weight',
        'Local Preference',
        'AS_PATH',
        'MED',
        'Origin Code',
        'Router ID',
        'Next-Hop IP',
      ],
      blanks: [
        { id: 'blank_1', position: 1, placeholder: 'Attribute แรกสุด (Cisco)', correct_word: 'Weight' },
        { id: 'blank_2', position: 2, placeholder: 'Attribute ใน iBGP (100)', correct_word: 'Local Preference' },
        { id: 'blank_3', position: 3, placeholder: 'Attribute จำนวน AS ผ่านทาง', correct_word: 'AS_PATH' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-mat-001',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-01',
      topic_id: 'top-inet-01-1',
      chapter_title: 'Packet Forwarding',
      topic_title: 'Network Device Communication & OSI',
      question_text: 'จงจับคู่อุปกรณ์เครือข่ายกับชั้นการทำงาน (OSI Layer) และบทบาทหน้าที่หลักให้ถูกต้องตรงกัน',
      question_type: 'matching',
      difficulty: 'medium',
      status: 'published',
      is_ai_generated: false,
      matching_pairs: [
        { id: 'p1', left: 'Router (เราเตอร์)', right: 'Network Layer (Layer 3) - ค้นหาเส้นทางและ Forward แพ็กเก็ตตาม IP Address' },
        { id: 'p2', left: 'Switch L2 (สวิตช์เลเยอร์ 2)', right: 'Data Link Layer (Layer 2) - ส่งเฟรมข้อมูลตาม MAC Address Table' },
        { id: 'p3', left: 'Repeater / Hub (ฮับ)', right: 'Physical Layer (Layer 1) - ขยายสัญญาณไฟฟ้าหรือคลื่นแสง' },
        { id: 'p4', left: 'Next-Gen Firewall / WAF', right: 'Application Layer (Layer 7) - ตรวจสอบความปลอดภัยและเนื้อหาข้อมูลแอปพลิเคชัน' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-mat-002',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-03',
      topic_id: 'top-inet-03-2',
      chapter_title: 'Advanced STP Tuning',
      topic_title: 'Root Guard, PortFast & BPDU Guard',
      question_text: 'จงจับคู่ฟีเจอร์การป้องกันความปลอดภัยของ Spanning Tree (STP Toolkit) กับพฤติกรรมการทำงานให้ถูกต้อง',
      question_type: 'matching',
      difficulty: 'medium',
      status: 'published',
      is_ai_generated: false,
      matching_pairs: [
        { id: 'p1', left: 'PortFast', right: 'ข้ามสถานะ Listening/Learning เข้าสู่ Forwarding ทันที เหมาะสำหรับพอร์ตเชื่อมต่อ End Host' },
        { id: 'p2', left: 'BPDU Guard', right: 'ปิดพอร์ตเป็น Err-Disabled ทันทีหากได้รับ BPDU เพื่อป้องกัน Rogue Switch เชื่อมต่อพอร์ต Access' },
        { id: 'p3', left: 'Root Guard', right: 'ป้องกันไม่ให้พอร์ตกลายเป็น Root Port เมื่อได้รับ Superior BPDU จากสวิตช์ภายนอก' },
        { id: 'p4', left: 'Loop Guard', right: 'เปลี่ยนพอร์ตเป็น Loop-Inconsistent ป้องกันพอร์ต Block กลายเป็น Forwarding เมื่อ BPDU หายไป' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-mat-003',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-09',
      topic_id: 'top-inet-09-2',
      chapter_title: 'Advanced OSPF',
      topic_title: 'OSPF LSA Types 1 to 5',
      question_text: 'จงจับคู่ประเภทของ OSPF LSA (Link-State Advertisement) กับบทบาทและเราเตอร์ผู้สร้างให้ถูกต้อง',
      question_type: 'matching',
      difficulty: 'hard',
      status: 'published',
      is_ai_generated: false,
      matching_pairs: [
        { id: 'p1', left: 'LSA Type 1 (Router LSA)', right: 'สร้างโดยเราเตอร์ทุกตัวใน Area เพื่อบอกสถานะลิงก์ของตนเองภายใน Area' },
        { id: 'p2', left: 'LSA Type 2 (Network LSA)', right: 'สร้างโดย DR ในเครือข่าย Multiaccess เพื่อรายงานรายชื่อเราเตอร์ทั้งหมดใน Subnet' },
        { id: 'p3', left: 'LSA Type 3 (Summary LSA)', right: 'สร้างโดย ABR เพื่อโฆษณา Subnet ข้ามระหว่าง Area ต่างๆ' },
        { id: 'p4', left: 'LSA Type 5 (External LSA)', right: 'สร้างโดย ASBR เพื่อโฆษณาเส้นทางภายนอกที่ถูก Redistribute เข้ามาใน OSPF' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-mat-004',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-13',
      topic_id: 'top-inet-13-1',
      chapter_title: 'Multicast',
      topic_title: 'Multicast Addressing & IGMP',
      question_text: 'จงจับคู่หมายเลข Multicast IP Address กับกลุ่มการทำงานเฉพาะด้านให้ถูกต้อง',
      question_type: 'matching',
      difficulty: 'medium',
      status: 'published',
      is_ai_generated: false,
      matching_pairs: [
        { id: 'p1', left: '224.0.0.1', right: 'All Hosts / All Systems บน Local Subnet' },
        { id: 'p2', left: '224.0.0.2', right: 'All Routers บน Local Subnet' },
        { id: 'p3', left: '224.0.0.5', right: 'All OSPF Routers' },
        { id: 'p4', left: '224.0.0.6', right: 'All OSPF DR and BDR Routers' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'q-mat-005',
      subject_id: inet.subject.id,
      chapter_id: 'ch-inet-14',
      topic_id: 'top-inet-14-3',
      chapter_title: 'QoS',
      topic_title: 'Classification, Marking & Policing/Shaping',
      question_text: 'จงจับคู่กลไกและมาตรฐานด้าน QoS (Quality of Service) กับคำอธิบายการทำงานให้ถูกต้อง',
      question_type: 'matching',
      difficulty: 'hard',
      status: 'published',
      is_ai_generated: false,
      matching_pairs: [
        { id: 'p1', left: 'Traffic Policing', right: 'ตัดทิ้ง (Drop) หรือ Re-mark แพ็กเก็ตที่ส่งเกินอัตราแบนด์วิดท์ที่กำหนดทันที' },
        { id: 'p2', left: 'Traffic Shaping', right: 'หน่วงเวลาและจัดเก็บแพ็กเก็ตส่วนเกินลงบัฟเฟอร์ เพื่อปรับอัตราส่งข้อมูลให้ราบเรียบสม่ำเสมอ' },
        { id: 'p3', left: 'Expedited Forwarding (EF - DSCP 46)', right: 'คลาสการส่งข้อมูลแบบ Low-Latency, Low-Jitter สูงสุด เหมาะสำหรับ Real-Time Voice/VoIP' },
        { id: 'p4', left: 'CoS (Class of Service)', right: 'ฟิลด์ 3 บิตใน 802.1Q VLAN Tag สำหรับระบุความสำคัญที่ Layer 2 (ค่า 0-7)' },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const extraKeys: QuestionAnswerKey[] = [
    {
      id: 'ak-fib-001',
      question_id: 'q-fib-001',
      correct_blank_answers: {
        blank_1: 'Transport Layer',
        blank_2: 'TCP',
        blank_3: 'UDP',
        blank_4: 'Network Layer',
      },
      explanation: 'Transport Layer จัดการการสื่อสาร End-to-End โดยมี TCP และ UDP เป็นโปรโตคอลหลัก ส่วน Network Layer จัดการเรื่อง IP Routing',
    },
    {
      id: 'ak-fib-002',
      question_id: 'q-fib-002',
      correct_blank_answers: {
        blank_1: 'FIB (Forwarding Information Base)',
        blank_2: 'Adjacency Table',
        blank_3: 'TCAM',
      },
      explanation: 'CEF ทำงานโดยสร้าง FIB Table จาก Routing Table และสร้าง Adjacency Table จาก ARP Table โดยโหลดเข้าฮาร์ดแวร์ TCAM เพื่อ Forward แพ็กเก็ตได้ที่ระดับ Line-Rate',
    },
    {
      id: 'ak-fib-003',
      question_id: 'q-fib-003',
      correct_blank_answers: {
        blank_1: 'Listening',
        blank_2: 'Learning',
        blank_3: 'Forwarding',
      },
      explanation: 'STP 802.1D ใช้เวลา 15s ในสถานะ Listening (รับฟัง BPDU) + 15s ในสถานะ Learning (เรียนรู้ MAC) รวม Forward Delay 30s ก่อนเข้าสู่ Forwarding',
    },
    {
      id: 'ak-fib-004',
      question_id: 'q-fib-004',
      correct_blank_answers: {
        blank_1: 'LACP',
        blank_2: 'Active',
        blank_3: 'Passive',
        blank_4: 'PAgP',
      },
      explanation: 'IEEE 802.3ad ใช้โปรโตคอล LACP โดยมีโหมด Active (เริ่มเจรจา) และ Passive (รอรับ) ส่วน Cisco ใช้ PAgP (Desirable / Auto)',
    },
    {
      id: 'ak-fib-005',
      question_id: 'q-fib-005',
      correct_blank_answers: {
        blank_1: 'Administrative Distance',
        blank_2: '1',
        blank_3: '90',
        blank_4: '110',
      },
      explanation: 'Administrative Distance (AD) กำหนดความน่าเชื่อถือของ Routing Source: Connected=0, Static=1, EIGRP Internal=90, OSPF=110, RIP=120, External BGP=20, Internal BGP=200',
    },
    {
      id: 'ak-fib-006',
      question_id: 'q-fib-006',
      correct_blank_answers: {
        blank_1: 'Reported Distance (RD)',
        blank_2: 'Feasible Distance (FD)',
        blank_3: 'Routing Loop',
      },
      explanation: 'EIGRP Feasibility Condition ระบุว่า Reported Distance (RD) < Feasible Distance (FD) เพื่อรับประกันความเป็น Loop-Free Topology อย่างสมบูรณ์',
    },
    {
      id: 'ak-fib-007',
      question_id: 'q-fib-007',
      correct_blank_answers: {
        blank_1: 'Weight',
        blank_2: 'Local Preference',
        blank_3: 'AS_PATH',
      },
      explanation: 'ลำดับ BGP Best-Path Selection: 1. Highest Weight (Cisco only), 2. Highest Local Preference (Default 100), 3. Locally Originated, 4. Shortest AS_PATH',
    },
    {
      id: 'ak-mat-001',
      question_id: 'q-mat-001',
      correct_matching: {
        p1: 'p1',
        p2: 'p2',
        p3: 'p3',
        p4: 'p4',
      },
      explanation: 'Router ทำงานที่ Network Layer (L3), Switch ทำงานที่ Data Link Layer (L2), Hub ทำงานที่ Physical Layer (L1) และ Next-Gen Firewall/WAF ตรวจสอบที่ Application Layer (L7)',
    },
    {
      id: 'ak-mat-002',
      question_id: 'q-mat-002',
      correct_matching: {
        p1: 'p1',
        p2: 'p2',
        p3: 'p3',
        p4: 'p4',
      },
      explanation: 'PortFast เร่งการเชื่อมต่อ Host, BPDU Guard ตัดพอร์ต Access หากเจอ BPDU, Root Guard ป้องกัน Superior Root, Loop Guard ป้องกัน Unidirectional Link Loop',
    },
    {
      id: 'ak-mat-003',
      question_id: 'q-mat-003',
      correct_matching: {
        p1: 'p1',
        p2: 'p2',
        p3: 'p3',
        p4: 'p4',
      },
      explanation: 'LSA 1 (Router LSA) ภายใน Area, LSA 2 (Network LSA) สร้างโดย DR, LSA 3 (Summary LSA) สร้างโดย ABR ข้าม Area, LSA 5 (External LSA) สร้างโดย ASBR',
    },
    {
      id: 'ak-mat-004',
      question_id: 'q-mat-004',
      correct_matching: {
        p1: 'p1',
        p2: 'p2',
        p3: 'p3',
        p4: 'p4',
      },
      explanation: '224.0.0.1 = All Hosts, 224.0.0.2 = All Routers, 224.0.0.5 = All OSPF Routers, 224.0.0.6 = OSPF DR/BDR',
    },
    {
      id: 'ak-mat-005',
      question_id: 'q-mat-005',
      correct_matching: {
        p1: 'p1',
        p2: 'p2',
        p3: 'p3',
        p4: 'p4',
      },
      explanation: 'Policing ตัด Drop ทันทีเมื่อเกินอัตรา, Shaping พักในบัฟเฟอร์ให้ส่งราบเรียบ, DSCP 46 (EF) สำหรับ VoIP, CoS อยู่ใน 802.1Q Tag ระดับ L2',
    },
  ];

  const extraSources: QuestionSource[] = [
    {
      id: 'src-fib-001',
      question_id: 'q-fib-001',
      file_name: 'chapter-01-packet-forwarding.pdf',
      page_numbers: [3, 4],
      evidence_text: 'TCP/IP Architecture layers and core protocol responsibilities.',
    },
    {
      id: 'src-fib-002',
      question_id: 'q-fib-002',
      file_name: 'chapter-01-packet-forwarding.pdf',
      page_numbers: [15, 18],
      evidence_text: 'CEF Forwarding Architecture, FIB table, Adjacency Table and TCAM operation.',
    },
    {
      id: 'src-fib-003',
      question_id: 'q-fib-003',
      file_name: 'chapter-02-spanning-tree.pdf',
      page_numbers: [8, 12],
      evidence_text: '802.1D STP port states: Blocking, Listening, Learning and Forwarding timers.',
    },
    {
      id: 'src-fib-004',
      question_id: 'q-fib-004',
      file_name: 'chapter-05-vlan-trunks-etherchannel.pdf',
      page_numbers: [14, 16],
      evidence_text: 'EtherChannel protocols comparison: LACP Active/Passive and PAgP Desirable/Auto.',
    },
    {
      id: 'src-fib-005',
      question_id: 'q-fib-005',
      file_name: 'chapter-06-ip-routing-essentials.pdf',
      page_numbers: [5, 7],
      evidence_text: 'Administrative Distance default values for Static, EIGRP, and OSPF.',
    },
    {
      id: 'src-fib-006',
      question_id: 'q-fib-006',
      file_name: 'chapter-07-eigrp.pdf',
      page_numbers: [10, 13],
      evidence_text: 'EIGRP DUAL algorithm, Feasibility Condition and loop-free topology validation.',
    },
    {
      id: 'src-fib-007',
      question_id: 'q-fib-007',
      file_name: 'chapter-11-bgp.pdf',
      page_numbers: [20, 24],
      evidence_text: 'BGP Best Path Algorithm decision steps: Weight, Local Preference, AS_PATH.',
    },
    {
      id: 'src-mat-001',
      question_id: 'q-mat-001',
      file_name: 'chapter-01-packet-forwarding.pdf',
      page_numbers: [6, 8],
      evidence_text: 'Network devices mapped across OSI and TCP/IP stack layers.',
    },
    {
      id: 'src-mat-002',
      question_id: 'q-mat-002',
      file_name: 'chapter-03-advanced-stp-tuning.pdf',
      page_numbers: [5, 9],
      evidence_text: 'STP Toolkit: PortFast, BPDU Guard, Root Guard, Loop Guard mechanism.',
    },
    {
      id: 'src-mat-003',
      question_id: 'q-mat-003',
      file_name: 'chapter-09-advanced-ospf.pdf',
      page_numbers: [8, 11],
      evidence_text: 'OSPF LSA Type 1, 2, 3, 4, and 5 functions and originating routers.',
    },
    {
      id: 'src-mat-004',
      question_id: 'q-mat-004',
      file_name: 'chapter-13-multicast.pdf',
      page_numbers: [4, 7],
      evidence_text: 'Well-known IPv4 Multicast addresses 224.0.0.1, 224.0.0.2, 224.0.0.5, 224.0.0.6.',
    },
    {
      id: 'src-mat-005',
      question_id: 'q-mat-005',
      file_name: 'chapter-14-qos.pdf',
      page_numbers: [12, 16],
      evidence_text: 'QoS traffic policing vs shaping, DSCP EF class, and 802.1Q CoS marking.',
    },
  ];

  return {
    profiles: [studentUser, adminUser],
    user_sessions: [],
    password_history: [],
    auth_audit_logs: [],
    subjects: [inet.subject as Subject],
    chapters: inet.chapters as Chapter[],
    topics: inet.topics as Topic[],
    source_documents: inet.documents as SourceDocument[],
    source_pages: [],
    exam_blueprints: inet.blueprints as ExamBlueprint[],
    questions: [...extraQuestions, ...(inet.questions as Question[])],
    question_choices: inet.question_choices as QuestionChoice[],
    question_answer_keys: [...extraKeys, ...(inet.question_answer_keys as QuestionAnswerKey[])],
    question_sources: [...extraSources, ...(inet.question_sources as QuestionSource[])],
    question_quality_flags: [],
    exam_attempts: [],
    attempt_questions: [],
    attempt_answers: [],
    bookmarks: [],
    admin_audit_logs: [],
    generation_runs: [],
  };
}
